version: '3.8'

services:
  db:
    image: postgres
    container_name: pg_taskhub
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: taskhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    container_name: pgadmin_taskhub
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: juan@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:

    